name: society_finance
description: Society Financial Management App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  open_file: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
